name: stape
description: Stape - Dart/Flutter Library

version: 1.0.2

environment:
  sdk: ^3.0.3

repository: https://github.com/Sten435/stape_library

platforms:
  android:
  web:
  windows:

topics:
  - dart
  - extension
  - library

dependencies:
dev_dependencies:
  lints: ^2.0.0
