name: stape
description: A Dart/Flutter library that provides extension methods and
  properties to extend your codebase.

version: 1.0.4

environment:
  sdk: ^3.0.3

repository: https://github.com/Sten435/stape_library

platforms:
  ? android
  ? web
  ? windows

topics:
  - dart
  - extension
  - library

dependencies:
  test: ^1.24.3
dev_dependencies:
  lints: ^2.0.0
